### ISSUE TITLE
Returning "ValueError: Number of classes, 11, does not match size of target_names, 36. Try specifying the labels parameter"

### ISSUE THREAD

**Issue by alanchmiel** [housecricket/How-did-I-write-an-own-OCR-program-using-Keras-and-TensorFlow-in-Python#6]
When I run the code with 
```
python train_model.py --az A_Z_Handwritten_Data.csv --model trained_ocr.model
```

It progresses through Epoch 50/50, but then returns

```
[INFO] evaluating network...
Traceback (most recent call last):
  File "C:\Users\achmiel\Downloads\How-did-I-write-an-own-OCR-program-using-Keras-and-TensorFlow-in-Python-master\How-did-I-write-an-own-OCR-program-using-Keras-and-TensorFlow-in-Python-master\train_model.py", line 113, in <module>
    print(classification_report(testY.argmax(axis=1),
  File "C:\Users\achmiel\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\achmiel\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py", line 1991, in classification_report
    raise ValueError(
ValueError: Number of classes, 11, does not match size of target_names, 36. Try specifying the labels parameter
```

I understand that this means I have more target names than classes, but I don't know what is the root o the problem.

**Comment by housecricket** [comment]
Please check your dataset or contact me to support you.

**Comment by ramiz12h** [comment]
Did you solve the problem ??

**Comment by LapTQ** [comment]
I run it very well!
